apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend # deployment manages pods with such label
  template: # template for the pods
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-app
          image: vlysenkoamo/docker-devops-backend:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-env-config