apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector: # which pods are represented by this service
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort