version: '3.9'
services:
  devops-frontend:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/src
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    ports:
      - "3000:3000"
    networks:
      - devops-frontend-network

networks:
  devops-frontend-network:
    name: devops-frontend-network
