{
 "title": "Backend app",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rps per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (method, path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_errors_total[5m]))\n/\n(sum(rate(http_requests_total[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "error rate per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 *\n  sum(rate(http_requests_errors_total[5m])) by (method, path)\n/\n  sum(rate(http_requests_total[5m])) by (method, path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests duration 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(http_requests_duration_seconds_bucket[5m])) by (le, method, path)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "application memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_memory_bytes_usage/1000000", "legendFormat": "__auto" }
   ]
  }
 ]
}