apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend # deployment manages pods with such label
  template: # template for the pods
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-app
          image: vlysenkoamo/docker-devops-frontend:v1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-env-config