apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector: # which pods are represented by this service
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30090
  type: NodePort