replicaCount: 1

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    database: devops-course
    existingSecret: "{{ .Release.Name }}-postgresql-secret"
  primary:
    initdb:
      scriptsConfigMap: "{{ .Release.Name }}-db-init-script"
    extendedConfiguration: |
      ssl = off

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0
  sentinel:
    enabled: false
